import js from '@eslint/js';
import { defineConfig, globalIgnores } from 'eslint/config';
import prettier from 'eslint-config-prettier';
import jsxA11y from 'eslint-plugin-jsx-a11y';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';
import simpleImportSort from 'eslint-plugin-simple-import-sort';
import globals from 'globals';
import tseslint from 'typescript-eslint';

export default defineConfig([
  globalIgnores([
    'dist',
    'src/components/ui/**', // vendored shadcn/ui components
    'src/api/schema.d.ts', // generated from OpenAPI
    'src/routeTree.gen.ts', // generated by TanStack Router
  ]),

  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      tseslint.configs.strictTypeChecked,
      tseslint.configs.stylisticTypeChecked,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
      jsxA11y.flatConfigs.recommended,
      prettier, // must stay last so it can disable formatting rules
    ],
    languageOptions: {
      ecmaVersion: 2023,
      globals: globals.browser,
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    plugins: {
      'simple-import-sort': simpleImportSort,
    },
    rules: {
      'simple-import-sort/imports': 'error',
      'simple-import-sort/exports': 'error',

      // Keeps type-only imports erasable, which matters with erasableSyntaxOnly
      '@typescript-eslint/consistent-type-imports': ['error', { fixStyle: 'inline-type-imports' }],

      // onClick={() => void mutate()} is a legitimate pattern in JSX handlers
      '@typescript-eslint/no-misused-promises': [
        'error',
        { checksVoidReturn: { attributes: false } },
      ],

      // Power and energy values are interpolated into labels all over the UI
      '@typescript-eslint/restrict-template-expressions': ['error', { allowNumber: true }],

      // Timezone safety: local Date getters silently use the machine timezone
      'no-restricted-syntax': [
        'warn',
        {
          selector:
            'CallExpression[callee.property.name=/^(getHours|getMinutes|getDate|getMonth|getDay|getFullYear)$/]',
          message:
            'Local Date getters ignore the timezone. Use TZDate or Intl.DateTimeFormat with Europe/Prague.',
        },
      ],

      'no-restricted-imports': [
        'error',
        { paths: [{ name: 'moment', message: 'Use date-fns instead.' }] },
      ],
    },
  },

  // Config files run in Node and are not part of the app tsconfig project
  {
    files: ['**/*.config.{js,ts}'],
    extends: [tseslint.configs.disableTypeChecked],
  },
]);
