/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Register a new user with the given email and password.
         */
        post: operations["auth-register-post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticate user and return a JWT access token.
         */
        post: operations["auth-login-post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description Refresh the JWT access token using a valid refresh token.
         */
        post: operations["auth-refresh-post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Invalidate the refresh token, effectively logging the user out.
         */
        post: operations["auth-logout-post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Me
         * @description Get the current authenticated user's information.
         */
        get: operations["auth-get_me-get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Users
         * @description List users with pagination. Requires admin privileges.
         */
        get: operations["users-list_users-get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User
         * @description Get a user by ID. Requires admin privileges.
         */
        get: operations["users-get_user-get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List My Sites
         * @description List all sites that the current user is a member of.
         */
        get: operations["sites-list_my_sites-get"];
        put?: never;
        /**
         * Create Site
         * @description Create a new site and assign the current user as the owner.
         */
        post: operations["sites-create_site-post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sites/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List All Sites
         * @description List all sites in the system. Requires admin privileges.
         */
        get: operations["sites-list_all_sites-get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sites/{site_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Site
         * @description Fetch a site by its ID, ensuring the current user has access.
         */
        get: operations["sites-get_site-get"];
        put?: never;
        post?: never;
        /**
         * Delete Site
         * @description Delete a site by its ID, ensuring the current user is the owner.
         */
        delete: operations["sites-delete_site-delete"];
        options?: never;
        head?: never;
        /**
         * Update Site
         * @description Update site details, ensuring the current user has the appropriate role.
         */
        patch: operations["sites-update_site-patch"];
        trace?: never;
    };
    "/api/v1/sites/{site_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Members
         * @description List all members of a site, ensuring the current user has access.
         */
        get: operations["sites-list_members-get"];
        put?: never;
        /**
         * Add Member
         * @description Add a new member to a site, ensuring the current user is the owner.
         */
        post: operations["sites-add_member-post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sites/{site_id}/members/{membership_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove Member
         * @description Remove a member from a site, ensuring the current user is the owner.
         */
        delete: operations["sites-remove_member-delete"];
        options?: never;
        head?: never;
        /**
         * Update Member Role
         * @description Update the role of a site member, ensuring the current user is the owner.
         */
        patch: operations["sites-update_member_role-patch"];
        trace?: never;
    };
    "/api/v1/sites/{site_id}/devices/pv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Pv Device
         * @description Create a new photovoltaic (solar panel) device for a specific site.
         */
        post: operations["devices-create_pv_device-post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sites/{site_id}/devices/pv/{device_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Pv Device
         * @description Update an existing photovoltaic (solar panel) device for a specific site.
         */
        patch: operations["devices-update_pv_device-patch"];
        trace?: never;
    };
    "/api/v1/sites/{site_id}/devices/battery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Battery Device
         * @description Create a new battery energy storage device for a specific site.
         */
        post: operations["devices-create_battery_device-post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sites/{site_id}/devices/battery/{device_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Battery Device
         * @description Update an existing battery energy storage device for a specific site.
         */
        patch: operations["devices-update_battery_device-patch"];
        trace?: never;
    };
    "/api/v1/sites/{site_id}/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Devices
         * @description List all devices for a specific site.
         */
        get: operations["devices-list_devices-get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sites/{site_id}/devices/{device_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Device
         * @description Retrieve a device by its ID for a specific site.
         */
        get: operations["devices-get_device-get"];
        put?: never;
        post?: never;
        /**
         * Delete Device
         * @description Delete a device by its ID for a specific site.
         */
        delete: operations["devices-delete_device-delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ote/fetch-prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fetch Prices
         * @description Manually trigger fetching and storing OTE spot prices. Requires admin privileges.
         */
        post: operations["ote-fetch_prices-post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sites/{site_id}/weather/fetch-forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fetch Weather Forecast
         * @description Fetch the weather forecast for a specific site and store it in the database.
         */
        post: operations["weather-fetch_weather_forecast-post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sites/{site_id}/simulation/pv/{device_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Simulate Pv
         * @description Simulate PV generation for a specific device at a site.
         */
        post: operations["simulation-simulate_pv-post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sites/{site_id}/appliances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Appliances
         * @description List all appliances for a specific site.
         */
        get: operations["appliances-list_appliances-get"];
        put?: never;
        /**
         * Create Appliance
         * @description Create a new appliance for a specific site.
         */
        post: operations["appliances-create_appliance-post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sites/{site_id}/appliances/{appliance_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Appliance
         * @description Retrieve an appliance by its ID.
         */
        get: operations["appliances-get_appliance-get"];
        put?: never;
        post?: never;
        /**
         * Delete Appliance
         * @description Delete an appliance by its ID.
         */
        delete: operations["appliances-delete_appliance-delete"];
        options?: never;
        head?: never;
        /**
         * Update Appliance
         * @description Update an existing appliance's details.
         */
        patch: operations["appliances-update_appliance-patch"];
        trace?: never;
    };
    "/api/v1/sites/{site_id}/appliances/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Load Forecast
         * @description Generate and store the expected load forecast for this site.
         */
        post: operations["appliances-generate_load_forecast-post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ApplianceBehavior
         * @description Enum representing the behavior of an appliance.
         * @enum {string}
         */
        ApplianceBehavior: "constant" | "cyclic" | "scheduled" | "on_demand";
        /**
         * ApplianceCreate
         * @description Schema for creating a new appliance.
         */
        ApplianceCreate: {
            /** Name */
            name: string;
            /** Powerw */
            powerW: number;
            /**
             * Standbypowerw
             * @default 0
             */
            standbyPowerW: number;
            /**
             * Priority
             * @default 1
             */
            priority: number;
            /**
             * Isshiftable
             * @default false
             */
            isShiftable: boolean;
            /** Config */
            config: components["schemas"]["ConstantConfig"] | components["schemas"]["CyclicConfig"] | components["schemas"]["ScheduledConfig"] | components["schemas"]["OnDemandConfig"];
        };
        /**
         * ApplianceRead
         * @description Schema for reading an appliance from the database.
         */
        ApplianceRead: {
            /** Id */
            id: number;
            /** Siteid */
            siteId: number;
            /** Name */
            name: string;
            behavior: components["schemas"]["ApplianceBehavior"];
            /** Powerw */
            powerW: number;
            /** Standbypowerw */
            standbyPowerW: number;
            /** Priority */
            priority: number;
            /** Isshiftable */
            isShiftable: boolean;
            /** Config */
            config: components["schemas"]["ConstantConfig"] | components["schemas"]["CyclicConfig"] | components["schemas"]["ScheduledConfig"] | components["schemas"]["OnDemandConfig"];
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /**
         * ApplianceUpdate
         * @description Schema for updating an existing appliance.
         */
        ApplianceUpdate: {
            /** Name */
            name?: string | null;
            /** Powerw */
            powerW?: number | null;
            /** Standbypowerw */
            standbyPowerW?: number | null;
            /** Priority */
            priority?: number | null;
            /** Isshiftable */
            isShiftable?: boolean | null;
            /** Config */
            config?: (components["schemas"]["ConstantConfig"] | components["schemas"]["CyclicConfig"] | components["schemas"]["ScheduledConfig"] | components["schemas"]["OnDemandConfig"]) | null;
        };
        /**
         * BatteryDeviceCreate
         * @description Battery energy storage device creation schema.
         */
        BatteryDeviceCreate: {
            /** Name */
            name: string;
            /** Capacitykwh */
            capacityKwh: number;
            /** Maxchargepowerkw */
            maxChargePowerKw: number;
            /** Maxdischargepowerkw */
            maxDischargePowerKw: number;
        };
        /**
         * BatteryDeviceRead
         * @description Battery energy storage device read schema.
         */
        BatteryDeviceRead: {
            /** Id */
            id: number;
            /** Siteid */
            siteId: number;
            /** Name */
            name: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "battery";
            /** Capacitykwh */
            capacityKwh: number;
            /** Maxchargepowerkw */
            maxChargePowerKw: number;
            /** Maxdischargepowerkw */
            maxDischargePowerKw: number;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /**
         * BatteryDeviceUpdate
         * @description Battery energy storage device update schema.
         */
        BatteryDeviceUpdate: {
            /** Name */
            name?: string | null;
            /** Capacitykwh */
            capacityKwh?: number | null;
            /** Maxchargepowerkw */
            maxChargePowerKw?: number | null;
            /** Maxdischargepowerkw */
            maxDischargePowerKw?: number | null;
        };
        /** Body_auth-login-post */
        "Body_auth-login-post": {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /**
         * ConstantConfig
         * @description Schema for appliances with constant behavior.
         */
        ConstantConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            behavior: "constant";
        };
        /**
         * CyclicConfig
         * @description Schema for appliances with cyclic behavior.
         */
        CyclicConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            behavior: "cyclic";
            /** Activeminutesmin */
            activeMinutesMin: number;
            /** Activeminutesmax */
            activeMinutesMax: number;
            /** Standbyminutesmin */
            standbyMinutesMin: number;
            /** Standbyminutesmax */
            standbyMinutesMax: number;
        };
        /**
         * ErrorDetail
         * @description The error detail model for API responses.
         */
        ErrorDetail: {
            /** Message */
            message: string;
            /** Code */
            code: string;
            /** Fields */
            fields?: {
                [key: string]: string[];
            } | null;
        };
        /**
         * ErrorResponse
         * @description The error response model for API responses.
         */
        ErrorResponse: {
            error: components["schemas"]["ErrorDetail"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * OTEFetchPricesResponse
         * @description Schema for the fetch-prices endpoint response.
         */
        OTEFetchPricesResponse: {
            /** Pointswritten */
            pointsWritten: number;
        };
        /**
         * OnDemandConfig
         * @description Schema for appliances with on-demand behavior.
         */
        OnDemandConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            behavior: "on_demand";
            /** Windows */
            windows: components["schemas"]["TimeWindow"][];
            /**
             * Maxusesperwindow
             * @default 1
             */
            maxUsesPerWindow: number;
        };
        /**
         * PVDeviceCreate
         * @description Photovoltaic (solar panel) device creation schema.
         */
        PVDeviceCreate: {
            /** Name */
            name: string;
            /** Installedpowerkwp */
            installedPowerKwp: number;
            /** Inverterpowerkw */
            inverterPowerKw: number;
            /** Tiltdegrees */
            tiltDegrees: number;
            /** Azimuthdegrees */
            azimuthDegrees: number;
        };
        /**
         * PVDeviceRead
         * @description Photovoltaic (solar panel) device read schema.
         */
        PVDeviceRead: {
            /** Id */
            id: number;
            /** Siteid */
            siteId: number;
            /** Name */
            name: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "pv";
            /** Installedpowerkwp */
            installedPowerKwp: number;
            /** Inverterpowerkw */
            inverterPowerKw: number;
            /** Tiltdegrees */
            tiltDegrees: number;
            /** Azimuthdegrees */
            azimuthDegrees: number;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /**
         * PVDeviceUpdate
         * @description Photovoltaic (solar panel) device update schema.
         */
        PVDeviceUpdate: {
            /** Name */
            name?: string | null;
            /** Installedpowerkwp */
            installedPowerKwp?: number | null;
            /** Inverterpowerkw */
            inverterPowerKw?: number | null;
            /** Tiltdegrees */
            tiltDegrees?: number | null;
            /** Azimuthdegrees */
            azimuthDegrees?: number | null;
        };
        /**
         * PVGenerationPoint
         * @description Represents a single point of PV generation data.
         */
        PVGenerationPoint: {
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /** Power Kw */
            power_kw: number;
        };
        /**
         * PVSimulationResult
         * @description Represents the result of a PV simulation.
         */
        PVSimulationResult: {
            /** Device Id */
            device_id: number;
            /** Site Id */
            site_id: number;
            /** Points */
            points: components["schemas"]["PVGenerationPoint"][];
            /** Total Energy Kwh */
            total_energy_kwh: number;
        };
        /**
         * RefreshRequest
         * @description Pydantic model for refresh token request.
         */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /**
         * RegisterRequest
         * @description Pydantic model for user registration request.
         */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Firstname */
            firstName: string;
            /** Lastname */
            lastName: string;
        };
        /**
         * ScheduledConfig
         * @description Schema for appliances with scheduled behavior.
         */
        ScheduledConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            behavior: "scheduled";
            /** Windows */
            windows: components["schemas"]["TimeWindow"][];
        };
        /**
         * SiteCreate
         * @description Schema for creating a new site.
         */
        SiteCreate: {
            /** Name */
            name: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
        };
        /**
         * SiteListResponse
         * @description Schema for listing sites with pagination.
         */
        SiteListResponse: {
            /** Items */
            items: components["schemas"]["SiteRead"][];
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
        };
        /**
         * SiteMembershipCreate
         * @description Schema for creating a new site membership.
         */
        SiteMembershipCreate: {
            /** Userid */
            userId: number;
            role: components["schemas"]["SiteRole"];
        };
        /**
         * SiteMembershipRead
         * @description Schema for reading site membership information.
         */
        SiteMembershipRead: {
            /** Id */
            id: number;
            /** Userid */
            userId: number;
            /** Siteid */
            siteId: number;
            role: components["schemas"]["SiteRole"];
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /**
         * SiteMembershipUpdate
         * @description Schema for updating site membership information.
         */
        SiteMembershipUpdate: {
            role: components["schemas"]["SiteRole"];
        };
        /**
         * SiteRead
         * @description Schema for reading site information.
         */
        SiteRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /**
         * SiteRole
         * @description Enumeration of roles that can be assigned to users within a site.
         * @enum {string}
         */
        SiteRole: "owner" | "manager" | "viewer";
        /**
         * SiteUpdate
         * @description Schema for updating site information.
         */
        SiteUpdate: {
            /** Name */
            name?: string | null;
            /** Latitude */
            latitude?: number | null;
            /** Longitude */
            longitude?: number | null;
        };
        /**
         * TimeWindow
         * @description Schema representing a time window for scheduled or on-demand appliances.
         */
        TimeWindow: {
            /** Starthour */
            startHour: number;
            /** Endhour */
            endHour: number;
            /** Probability */
            probability: number;
            /** Durationminutesmin */
            durationMinutesMin: number;
            /** Durationminutesmax */
            durationMinutesMax: number;
        };
        /**
         * TokenResponse
         * @description Pydantic model for token response.
         */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /**
         * UserListResponse
         * @description Pydantic model for listing users.
         */
        UserListResponse: {
            /** Items */
            items: components["schemas"]["UserRead"][];
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
        };
        /**
         * UserRead
         * @description Pydantic model for reading user data.
         */
        UserRead: {
            /** Id */
            id: number;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Firstname */
            firstName: string;
            /** Lastname */
            lastName: string;
            role: components["schemas"]["UserRole"];
            /** Isactive */
            isActive: boolean;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /**
         * UserRole
         * @description Enumeration of user roles in the system.
         * @enum {string}
         */
        UserRole: "admin" | "user";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "auth-register-post": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Resource already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "auth-login-post": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_auth-login-post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "auth-refresh-post": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "auth-logout-post": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "auth-get_me-get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "users-list_users-get": {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "users-get_user-get": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "sites-list_my_sites-get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteRead"][];
                };
            };
        };
    };
    "sites-create_site-post": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SiteCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "sites-list_all_sites-get": {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "sites-get_site-get": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "sites-delete_site-delete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "sites-update_site-patch": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SiteUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "sites-list_members-get": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteMembershipRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "sites-add_member-post": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SiteMembershipCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteMembershipRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "sites-remove_member-delete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
                membership_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "sites-update_member_role-patch": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
                membership_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SiteMembershipUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteMembershipRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "devices-create_pv_device-post": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PVDeviceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PVDeviceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "devices-update_pv_device-patch": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
                device_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PVDeviceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PVDeviceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "devices-create_battery_device-post": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatteryDeviceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatteryDeviceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "devices-update_battery_device-patch": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
                device_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatteryDeviceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatteryDeviceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "devices-list_devices-get": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": (components["schemas"]["PVDeviceRead"] | components["schemas"]["BatteryDeviceRead"])[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "devices-get_device-get": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
                device_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PVDeviceRead"] | components["schemas"]["BatteryDeviceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "devices-delete_device-delete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
                device_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "ote-fetch_prices-post": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OTEFetchPricesResponse"];
                };
            };
        };
    };
    "weather-fetch_weather_forecast-post": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "simulation-simulate_pv-post": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
                device_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PVSimulationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "appliances-list_appliances-get": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplianceRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "appliances-create_appliance-post": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplianceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplianceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "appliances-get_appliance-get": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
                appliance_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplianceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "appliances-delete_appliance-delete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
                appliance_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "appliances-update_appliance-patch": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
                appliance_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplianceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplianceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "appliances-generate_load_forecast-post": {
        parameters: {
            query?: {
                hours?: number;
            };
            header?: never;
            path: {
                site_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
