"""add role to users

Revision ID: 0ed5ee726992
Revises: 764e6663ae93
Create Date: 2026-07-10 18:00:54.204908

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0ed5ee726992"
down_revision: str | Sequence[str] | None = "764e6663ae93"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

user_role_enum = sa.Enum("admin", "user", name="user_role")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    user_role_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "users",
        sa.Column(
            "role",
            user_role_enum,
            server_default="user",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    user_role_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
