"""Add battery efficiency and SoC fields.

Revision ID: 16db863955a4
Revises: c5e183f08d5a
Create Date: 2026-07-29 15:28:31.716505

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "16db863955a4"
down_revision: str | Sequence[str] | None = "c5e183f08d5a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "battery_devices",
        sa.Column("charge_efficiency", sa.Float(), nullable=False, server_default="0.95"),
    )
    op.add_column(
        "battery_devices",
        sa.Column("discharge_efficiency", sa.Float(), nullable=False, server_default="0.95"),
    )
    op.add_column(
        "battery_devices",
        sa.Column("min_soc_percent", sa.Float(), nullable=False, server_default="20.0"),
    )
    op.add_column(
        "battery_devices",
        sa.Column("current_soc_kwh", sa.Float(), nullable=False, server_default="0.0"),
    )

    # Remove server defaults after adding the columns
    # to avoid future insertions using the default values
    op.alter_column("battery_devices", "charge_efficiency", server_default=None)
    op.alter_column("battery_devices", "discharge_efficiency", server_default=None)
    op.alter_column("battery_devices", "min_soc_percent", server_default=None)
    op.alter_column("battery_devices", "current_soc_kwh", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("battery_devices", "current_soc_kwh")
    op.drop_column("battery_devices", "min_soc_percent")
    op.drop_column("battery_devices", "discharge_efficiency")
    op.drop_column("battery_devices", "charge_efficiency")
    # ### end Alembic commands ###
