"""Add risk profile enum and risk_profile enum column on Site.

Revision ID: 218b191f0a33
Revises: 242c3413d30b
Create Date: 2026-08-22 15:34:09.102177

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "218b191f0a33"
down_revision: str | Sequence[str] | None = "242c3413d30b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

risk_profile_enum = sa.Enum("low", "medium", "high", name="risk_profile")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    risk_profile_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "sites",
        sa.Column(
            "risk_profile",
            sa.Enum("low", "medium", "high", name="risk_profile"),
            nullable=False,
            server_default="medium",
        ),
    )
    op.alter_column("sites", "risk_profile", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sites", "risk_profile")
    risk_profile_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
