"""Add import_surcharge_czk_per_kwh and export_price_ratio columns to sites table.

Revision ID: 242c3413d30b
Revises: 16db863955a4
Create Date: 2026-08-22 13:42:57.741330

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "242c3413d30b"
down_revision: str | Sequence[str] | None = "16db863955a4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sites",
        sa.Column("import_surcharge_czk_per_kwh", sa.Float(), nullable=False, server_default="2.5"),
    )
    op.add_column(
        "sites", sa.Column("export_price_ratio", sa.Float(), nullable=False, server_default="1.0")
    )
    op.alter_column("sites", "import_surcharge_czk_per_kwh", server_default=None)
    op.alter_column("sites", "export_price_ratio", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sites", "export_price_ratio")
    op.drop_column("sites", "import_surcharge_czk_per_kwh")
    # ### end Alembic commands ###
