"""Add devices, pv_devices and battery_devices tables.

Revision ID: 385e354b592e
Revises: a3f2f9835d36
Create Date: 2026-07-11 17:28:41.309157

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "385e354b592e"
down_revision: str | Sequence[str] | None = "a3f2f9835d36"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

device_type_enum = sa.Enum("pv", "battery", name="device_type")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "devices",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("type", device_type_enum, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_devices_site_id"), "devices", ["site_id"], unique=False)
    op.create_table(
        "battery_devices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("capacity_kwh", sa.Float(), nullable=False),
        sa.Column("max_charge_power_kw", sa.Float(), nullable=False),
        sa.Column("max_discharge_power_kw", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pv_devices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("installed_power_kwp", sa.Float(), nullable=False),
        sa.Column("tilt_degrees", sa.Float(), nullable=False),
        sa.Column("azimuth_degrees", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pv_devices")
    op.drop_table("battery_devices")
    op.drop_index(op.f("ix_devices_site_id"), table_name="devices")
    op.drop_table("devices")
    device_type_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
