"""Add sites and site_memberships tables.

Revision ID: 4dd2aa16cd35
Revises: 0ed5ee726992
Create Date: 2026-07-11 10:11:17.961668

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4dd2aa16cd35"
down_revision: str | Sequence[str] | None = "0ed5ee726992"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

site_role_enum = sa.Enum("owner", "manager", "viewer", name="site_role")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sites",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "site_memberships",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("role", site_role_enum, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("site_id", "user_id", name="uq_user_site"),
    )
    op.create_index(
        op.f("ix_site_memberships_site_id"), "site_memberships", ["site_id"], unique=False
    )
    op.create_index(
        op.f("ix_site_memberships_user_id"), "site_memberships", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_site_memberships_user_id"), table_name="site_memberships")
    op.drop_index(op.f("ix_site_memberships_site_id"), table_name="site_memberships")
    op.drop_table("site_memberships")
    op.drop_table("sites")
    site_role_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
