"""Add inverter_power_kw to pv_devices.

Revision ID: 54913907321b
Revises: 4c8fec19d0e5
Create Date: 2026-07-15 20:03:49.530213

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "54913907321b"
down_revision: str | Sequence[str] | None = "4c8fec19d0e5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pv_devices", sa.Column("inverter_power_kw", sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pv_devices", "inverter_power_kw")
    # ### end Alembic commands ###
