"""add first_name and last_name to users

Revision ID: 94ebc7bc64ee
Revises: ec0f985b7b68
Create Date: 2026-07-08 21:14:20.676175

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "94ebc7bc64ee"
down_revision: str | Sequence[str] | None = "ec0f985b7b68"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("first_name", sa.String(length=100), nullable=False))
    op.add_column("users", sa.Column("last_name", sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")
    # ### end Alembic commands ###
