"""Add appliances table.

Revision ID: c5e183f08d5a
Revises: 54913907321b
Create Date: 2026-07-16 20:06:00.577645

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c5e183f08d5a"
down_revision: str | Sequence[str] | None = "54913907321b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

appliance_behavior_enum = sa.Enum(
    "constant",
    "cyclic",
    "scheduled",
    "on_demand",
    name="appliance_behavior",
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "appliances",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("behavior", appliance_behavior_enum, nullable=False),
        sa.Column("power_w", sa.Float(), nullable=False),
        sa.Column("standby_power_w", sa.Float(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("is_shiftable", sa.Boolean(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_appliances_site_id"), "appliances", ["site_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_appliances_site_id"), table_name="appliances")
    op.drop_table("appliances")
    appliance_behavior_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
