"""Add battery state of charge bounds and efficiency.

Revision ID: dd221dfdb7af
Revises: c5e183f08d5a
Create Date: 2026-09-07 11:10:24.007262

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dd221dfdb7af"
down_revision: str | Sequence[str] | None = "c5e183f08d5a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "battery_devices",
        sa.Column("min_state_of_charge", sa.Float(), server_default="0.1", nullable=False),
    )
    op.add_column(
        "battery_devices",
        sa.Column("max_state_of_charge", sa.Float(), server_default="1.0", nullable=False),
    )
    op.add_column(
        "battery_devices",
        sa.Column("round_trip_efficiency", sa.Float(), server_default="0.9", nullable=False),
    )
    op.create_check_constraint(
        "chk_battery_soc_range", "battery_devices", "min_state_of_charge < max_state_of_charge"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("chk_battery_soc_range", "battery_devices", type_="check")
    op.drop_column("battery_devices", "round_trip_efficiency")
    op.drop_column("battery_devices", "max_state_of_charge")
    op.drop_column("battery_devices", "min_state_of_charge")
    # ### end Alembic commands ###
