"""Add max length to email field, add hashed_password and created_at fields.

Revision ID: ec0f985b7b68
Revises: b73ca7d56fb2
Create Date: 2026-07-02 21:00:23.577528

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ec0f985b7b68"
down_revision: str | Sequence[str] | None = "b73ca7d56fb2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("hashed_password", sa.String(length=255), nullable=False))
    op.add_column("users", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.alter_column(
        "users",
        "email",
        type_=sa.String(length=255),
        existing_type=sa.String(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "created_at")
    op.drop_column("users", "hashed_password")
    op.alter_column(
        "users",
        "email",
        type_=sa.String(),
        existing_type=sa.String(length=255),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
