"""One-off import of the measured history from InfluxDB into TimescaleDB.

Only the series that cannot be recreated are carried over: spot prices (the OTE
API serves only today and tomorrow) and battery states. Forecasts and weather are
regenerated by the scheduled jobs.

InfluxDB is read over its HTTP API one UTC day at a time, which keeps every query
under the Parquet file limit of InfluxDB 3 Core. Rows are upserted, so the import
can be run again after an interruption.

Usage:
    uv run python -m src.import_influx_history [--since 2026-07-01]

Reads INFLUXDB_HOST, INFLUXDB_TOKEN and INFLUXDB_DATABASE from the environment.
Delete this module together with the InfluxDB service once the import is done.
"""

import argparse
import asyncio
import logging
import os
from collections.abc import Callable
from datetime import UTC, date, datetime, timedelta
from typing import Any

import httpx
from sqlalchemy import select

import src.core.models_registry  # noqa: F401 - resolves the foreign keys between models
from src.core.database import Base, SessionLocal, engine
from src.core.timeseries import upsert
from src.devices.models import BatteryState, Device
from src.ote.models import OTESpotPrice

logging.basicConfig(level=logging.INFO, format="%(message)s")
logger = logging.getLogger(__name__)
logging.getLogger("httpx").setLevel(logging.WARNING)


def _time(row: dict[str, Any]) -> datetime:
    # InfluxDB returns naive timestamps that are already UTC.
    return datetime.fromisoformat(row["time"]).replace(tzinfo=UTC)


def _ote_row(row: dict[str, Any]) -> dict[str, Any]:
    return {
        "time": _time(row),
        "price_czk_mwh": float(row["price_czk_mwh"]),
        "price_eur_mwh": float(row["price_eur_mwh"]),
        "level": row["level"],
        "level_num_96": int(row["level_num_96"]),
    }


def _battery_row(row: dict[str, Any]) -> dict[str, Any]:
    return {
        "device_id": int(row["device_id"]),
        "time": _time(row),
        "state_of_charge_kwh": float(row["state_of_charge_kwh"]),
        # States written before setpoints were recorded carry none: an idle battery.
        "charge_kw": float(row.get("charge_kw") or 0.0),
        "discharge_kw": float(row.get("discharge_kw") or 0.0),
    }


SERIES: dict[str, tuple[type[Base], Callable[[dict[str, Any]], dict[str, Any]]]] = {
    "ote_spot_price": (OTESpotPrice, _ote_row),
    "battery_state": (BatteryState, _battery_row),
}


class InfluxReader:
    """Minimal client for the InfluxDB 3 SQL endpoint."""

    def __init__(self) -> None:
        self._url = os.environ.get("INFLUXDB_HOST", "http://influxdb:8181") + "/api/v3/query_sql"
        self._database = os.environ.get("INFLUXDB_DATABASE", "ems")
        self._client = httpx.AsyncClient(
            headers={"Authorization": f"Bearer {os.environ['INFLUXDB_TOKEN']}"}, timeout=60
        )

    async def read_day(self, table: str, day: date) -> list[dict[str, Any]] | None:
        """Read one UTC day of a table, or None if the table does not exist."""
        start = datetime(day.year, day.month, day.day, tzinfo=UTC)
        # The table name is one of the constants in `SERIES`, never user input.
        query = f"SELECT * FROM {table} WHERE time >= $start AND time < $end"  # noqa: S608
        response = await self._client.post(
            self._url,
            json={
                "db": self._database,
                "q": query,
                "params": {
                    "start": start.isoformat(),
                    "end": (start + timedelta(days=1)).isoformat(),
                },
                "format": "json",
            },
        )
        if response.status_code == 400 and "not found" in response.text:
            return None
        response.raise_for_status()
        return response.json()

    async def close(self) -> None:
        """Close the underlying HTTP connection pool."""
        await self._client.aclose()


async def import_history(since: date, until: date) -> None:
    """Copy every day in [since, until] of each series into Postgres."""
    reader = InfluxReader()
    try:
        async with SessionLocal() as db:
            # A battery deleted since its states were written would fail the
            # foreign key; its history has nothing left to describe.
            existing_devices = set((await db.execute(select(Device.id))).scalars())

            for table, (model, convert) in SERIES.items():
                total = 0
                day = since
                while day <= until:
                    records = await reader.read_day(table, day)
                    if records is None:
                        logger.info(f"{table}: does not exist in InfluxDB, skipping.")
                        break

                    rows = [convert(record) for record in records]
                    if model is BatteryState:
                        rows = [row for row in rows if row["device_id"] in existing_devices]
                    skipped = len(records) - len(rows)

                    # A tag is part of a row's identity in InfluxDB, so a price
                    # whose `level` was reclassified between fetches was stored
                    # twice. The upsert keeps one row per step.
                    written = await upsert(db, model, rows)
                    await db.commit()
                    if records:
                        logger.info(
                            f"{table} {day}: {written} rows"
                            + (
                                f", {len(rows) - written} duplicates merged"
                                if len(rows) > written
                                else ""
                            )
                            + (f", {skipped} of deleted devices skipped" if skipped else "")
                        )
                    total += written
                    day += timedelta(days=1)

                logger.info(f"✅ {table}: {total} rows imported.")
    finally:
        await reader.close()
        await engine.dispose()


def main() -> None:
    """Parse the arguments and run the import."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--since",
        type=date.fromisoformat,
        default=date(2026, 7, 1),
        help="First UTC day to import (default: 2026-07-01).",
    )
    args = parser.parse_args()
    # Tomorrow's prices are already published by the afternoon.
    until = datetime.now(UTC).date() + timedelta(days=1)
    asyncio.run(import_history(args.since, until))


if __name__ == "__main__":
    main()
